// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ConsoleApp1
{
    public partial class Issue_classification
    {
        /// <summary>
        /// model input class for Issue_classification.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"ID")]
            public float ID { get; set; }

            [ColumnName(@"Area")]
            public string Area { get; set; }

            [ColumnName(@"Title")]
            public string Title { get; set; }

            [ColumnName(@"Description")]
            public string Description { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Issue_classification.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"ID")]
            public float ID { get; set; }

            [ColumnName(@"Area")]
            public uint Area { get; set; }

            [ColumnName(@"Title")]
            public float[] Title { get; set; }

            [ColumnName(@"Description")]
            public float[] Description { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("issue-classification.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
